### ISSUE TITLE
CSS Building Fails on RHEL 7

### ISSUE THREAD

**Issue by NorthernLights** [LINKIWI/modern-paste#22]
On Red Hat Enterprise Linux 7, CSS Building fails in both DEV Environment mode and PROD environment mode. The following is kicked back from the server shell:

`Javascript build complete.
python build/build_css.py --config-environment
Configuration in config.py specified a prod environment.
Compiling SCSS in minified mode.
CSS build started.
Compiling CSS app/static/scss/stylesheet.scss --> app/static/build/css/stylesheet.css
Traceback (most recent call last):
  File "build/build_css.py", line 79, in <module>
    '--style', style,
  File "/usr/lib64/python2.7/subprocess.py", line 524, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
make[1]: *** [default] Error 1
make[1]: Leaving directory `/home/<redacted>/public_html/onepaste'
make: *** [all] Error 2
[root@nexus01 onepaste]#
`
I have noticed the instructions for Modern Paste are for Ubuntu and Debian like all other private "pastebin" style scripts. Is this script even compatible with Enterprise Linux? I would think it would be once all the correct tooling is in place (yum groupinstall 'Development Tools'). Other environmental factors you should be aware of is that this is naturally being installed to a web server under its own subdomain.

We're trying to install this script to support our the gathering of log files for our very popular skin developed for the Kodi and Emby projects as most people do not feel comfortable sharing to pastebin.com (with good reason).

We have replicated this on 3 different RHEL 7 servers and a RHEL 7 VMWare vSphere Enterprise Plus VM.

**Comment by LINKIWI** [comment]
The installation instructions are indeed Debian-oriented as that as the only environment I've tested this on. That said, there *should* be no reason that it wouldn't run on enterprise Linux provided you have installed all the dependencies as you said.

As for the make failure, it's possible that the sass build step itself is failing because the `sass` executable isn't in `PATH`. I would guess this is why the script raises "no such file or directory." Can you try

```
(sudo) gem install sass
which sass  # should exit 0
sass app/static/scss/stylesheet.scss:app/static/build/css/stylesheet.css --style compressed
```

**Comment by LINKIWI** [comment]
In your traceback, it looks like the SCSS source directory is missing `scss` and has a mispelling of `stylesheet`. You have

```
sass app/static/stylesheet.scss:app/static/build/css/styleshee.css --style compressed
```

Can you try

```
sass app/static/scss/stylesheet.scss:app/static/build/css/stylesheet.css --style compressed
```

(This references a [SCSS file](https://github.com/LINKIWI/modern-paste/blob/master/app/static/scss/stylesheet.scss) in the repository tree)

If this succeeds, I'd be happy to accept a PR with notes on getting the make process working on RHEL.

**Comment by NorthernLights** [comment]
Sorry about that, I do that when having a lot of server connections open to different servers around the world. I did correct it by simply pasting it into PuTTy to prevent the mistake. It seems to succeed when doing it like that but when you run the `sudo make` process, the build still fails at the same position so I ran a backtrace of the stylesheet build which didn't report anything:

`[root@nexus01 onepaste]# sass app/static/scss/stylesheet.scss:app/static/build/css/stylesheet.css --style compressed
[root@nexus01 onepaste]#`

Likewise, in the build process:

`Javascript build complete.
python build/build_css.py --config-environment
Configuration in config.py specified a prod environment.
Compiling SCSS in minified mode.
CSS build started.
Compiling CSS app/static/scss/stylesheet.scss --> app/static/build/css/stylesheet.css
Traceback (most recent call last):
  File "build/build_css.py", line 79, in <module>
    '--style', style,
  File "/usr/lib64/python2.7/subprocess.py", line 524, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
make[1]: *** [default] Error 1
make[1]: Leaving directory `/home/REDACTED/public_html/onepaste'
make: *** [all] Error 2
[root@nexus01 onepaste]# sass app/static/scss/stylesheet.scss:app/static/build/css/stylesheet.css --style compressed --trace
[root@nexus01 onepaste]#`

**Comment by okgolove** [comment]
@NorthernLights where is your sass? /usr/local/bin?
Add /usr/local/bin to $PATH and try again.

**Comment by DMinsky** [comment]
Looks like the issue here is that /usr/local/bin is in $PATH for current user. But it isn't for root. So when you trying "to sudo" something like "sudo make" from installation instruction sass isn't accessible from $PATH.

**Comment by jfoots** [comment]
To fix this issue I did the following:
~~~
┌─[✗]─[jfoots@paste]─[~/modern-paste{master}]
└──> sudo which sass
which: no sass in (/sbin:/bin:/usr/sbin:/usr/bin)
┌─[✗]─[jfoots@paste]─[~/modern-paste{master}]
└──> sudo cp /usr/local/bin/sass* /usr/sbin/
┌─[jfoots@paste]─[~/modern-paste{master}]
└──> sudo which sass
/sbin/sass
~~~
After that the sudo make command finished accordingly. You could add that to $PATH as suggested above but it would be better to install sass so that it goes to sbin, if you didn't do that (like me) cp into the dir works just as well.
