### ISSUE TITLE
Unable to Pass the scss_lint check

### ISSUE THREAD

**Issue by jfoots** [LINKIWI/modern-paste#49]
When I run $ sudo make in the dir as directed I get the following:
~~~
pre-commit run --all-files
Trim Trailing Whitespace.................................................Passed
Check JSON...............................................................Passed
Check Yaml...............................................................Passed
Check for merge conflicts................................................Passed
Check python ast.........................................................Passed
Debug Statements (Python)................................................Passed
Fix End of Files.........................................................Passed
Flake8...................................................................Passed
Fix requirements.txt.....................................................Passed
scss_lint................................................................Failed
hookid: scss-lint

/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- json (LoadError)
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/share/gems/gems/scss_lint-0.54.0/lib/scss_lint/reporter/json_reporter.rb:1:in `<top (required)>'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/share/gems/gems/scss_lint-0.54.0/lib/scss_lint.rb:32:in `block in <top (required)>'
	from /usr/local/share/gems/gems/scss_lint-0.54.0/lib/scss_lint.rb:31:in `each'
	from /usr/local/share/gems/gems/scss_lint-0.54.0/lib/scss_lint.rb:31:in `<top (required)>'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/share/gems/gems/scss_lint-0.54.0/bin/scss-lint:3:in `<top (required)>'
	from /root/.pre-commit/repo1qACiZ/rbenv-default/gems/bin/scss-lint:22:in `load'
	from /root/.pre-commit/repo1qACiZ/rbenv-default/gems/bin/scss-lint:22:in `<main>'

make[1]: *** [Makefile:56: check-style] Error 1
make[1]: Leaving directory '/home/jfoots/modern-paste'
make: *** [Makefile:6: all] Error 2
~~~

Now that wouldn't be bad but I'm able to actually install the file manually using gem its only when run in the context of pre-commit run --all-files it fails. 

I've seen some articles that talk about changing the gemfile for it but I don't think that is the issue.

**Comment by jfoots** [comment]
Alright so after a few hours of testing any tidbit I could find. This was resolved by running the following:

~~~
$ sudo gem install json
~~~

After that install completed without issue.

Closing issue.
